### PR TITLE
Game in randome numbers

### PR DESCRIPTION
**Pull request by KulichenkoViacheslav**
Add a file main.c for the game in guess a random number

Signed-off-by: KulichenkoViacheslav <Kulichenko.Viacheslav@gmail.com>

### CODE REVIEW

**Comment by marynasergiyenko** [comment]
I did not understand why you set up "change request" label by yourself :), but you are right. 
Please rename comments for all commits in following way.
Topic: <Action> <the rest title text>
for example
Lesson 2 Part 1: Add ....

**Comment by KulichenkoViacheslav** [comment]
I corrected these comments.

**Comment by a-vodka** [comment]
You can not commit to a master. Please, create your own branch

**Comment by a-vodka** [comment]
Please, check code style for if statement
https://www.kernel.org/doc/html/v4.10/process/coding-style.html#placing-braces-and-spaces

**Review by a-vodka — APPROVED** [review]

**Comment by a-vodka** [comment]
OK

**Pull request merged**
